# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

target 'd214Pathways' do

  pod 'SwiftyJSON'
  pod 'Alamofire', '3.5.0'
  pod 'ChameleonFramework'

end
